
# 🧮 NumPy Mega Homework

This workbook contains **lots** of NumPy practice tasks, grouped by topic.  
For each task, write your solution in the empty code cell that follows it.

**Rules**
- Use **NumPy** (`import numpy as np`) for array operations.
- Do **not** use Python lists for computations unless explicitly asked.
- Add comments to explain key steps.

**Sections**
1. Array Basics & Creation (10 tasks)  
2. Indexing & Slicing (8 tasks)  
3. Array Operations & Broadcasting (8 tasks)  
4. Mathematical Functions (6 tasks)  
5. Aggregations & Descriptive Stats (6 tasks)  
6. Random Numbers & Simulations (8 tasks)  
7. Linear Algebra (6 tasks)  
8. Reshaping, Stacking & Splitting (5 tasks)  
9. Real‑World Mini Case Studies (7 tasks)


## 1) Array Basics & Creation

**1.1** Import NumPy as `np` and print the installed version.

In [1]:
import numpy as np
np.__version__

'2.4.4'

**1.2** Create a 1D array with values from 0 to 20 (inclusive).

In [2]:
arr = np.arange(0, 21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

**1.3** Create a 1D array of the first 15 even numbers.

In [4]:
arr = np.arange(0, 30, 2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

**1.4** Create a 3×3 array filled with 7s (use `np.full`).

In [5]:
matrix = np.full(shape=(3, 3), fill_value=7)
matrix

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

**1.5** Create a 5×5 identity matrix.

In [7]:
matrix = np.identity(5, dtype="int")
matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

**1.6** Create an array of 10 numbers linearly spaced between 0 and 1 (inclusive).

In [8]:
arr = np.linspace(start=0, stop=1, num=10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

**1.7** Create an array of 12 values logarithmically spaced between 10^0 and 10^3.

In [9]:
arr = np.logspace(start=2, stop=3, num=12, base=10)
arr

array([ 100.        ,  123.28467394,  151.9911083 ,  187.38174229,
        231.01297001,  284.80358684,  351.11917342,  432.87612811,
        533.66992312,  657.93322466,  811.13083079, 1000.        ])

**1.8** Create a boolean array of length 12 that alternates `True, False, True, False, ...`.

In [10]:
arr = np.tile([True, False], 6)
arr

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False])

**1.9** Create a 4×4 array of random integers from 10 to 99 (inclusive).

In [10]:
rng = np.random.default_rng(seed=1234)
arr = rng.integers(low=10, high=99, size=(4, 4), endpoint=True)
arr

array([[98, 97, 98, 44],
       [25, 93, 19, 33],
       [22, 38, 58, 20],
       [81, 31, 80, 38]])

**1.10** Given `a = np.array([1, 2, 3], dtype=np.int32)`, change its dtype to float64 without copying if possible.

In [12]:
a = np.array([1, 2, 3], dtype="int32")
a = a.astype(dtype="float64", copy=False)
a.dtype

dtype('float64')

## 2) Indexing & Slicing

**2.1** Create an array `x = np.arange(1, 26).reshape(5,5)`. Extract the **center 3×3 block**.

In [15]:
x = np.arange(1, 26).reshape(5, 5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [23]:
center = x[1:-1, 1:-1]
center

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

**2.2** From `x` above, extract the **border elements** (top row, bottom row, leftmost column, rightmost column) into a 1D array.

In [25]:
mask = np.ones(shape=x.shape, dtype="bool")  # all True mask with the shape of original matrix
mask[1:-1, 1:-1] = False
x[mask]

array([ 1,  2,  3,  4,  5,  6, 10, 11, 15, 16, 20, 21, 22, 23, 24, 25])

**2.3** From `x`, select every other row and every other column.

In [26]:
mask = np.zeros(shape=x.shape, dtype="bool")
mask[1:-1, 1:-1] = True
x[mask]

array([ 7,  8,  9, 12, 13, 14, 17, 18, 19])

**2.4** Given `y = np.arange(10)`, reverse it using slicing only.

In [27]:
y = np.arange(10)
y[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

**2.5** From `y`, extract elements with **odd indices** (1,3,5,...) using slicing.

In [28]:
y[1::2]

array([1, 3, 5, 7, 9])

**2.6** Use **fancy indexing** to pick elements at indices `[0, 3, 7]` from `y`.

In [30]:
y[[0, 3, 7]]

array([0, 3, 7])

**2.7** Given `z = np.array([3, -1, 7, 0, -5, 2])`, replace **negative** values with `0` using boolean indexing.

In [31]:
z = np.array([3, -1, 7, 0, -5, 2])
mask = z < 0
z[mask] = 0
z

array([3, 0, 7, 0, 0, 2])

**2.8** Given `M = np.arange(1,17).reshape(4,4)`, set the **diagonal** to `-1` without a loop.

In [33]:
M = np.arange(1, 17).reshape(4, 4)
M[[0, 1, 2, 3], [0, 1, 2, 3]] = -1
M

array([[-1,  2,  3,  4],
       [ 5, -1,  7,  8],
       [ 9, 10, -1, 12],
       [13, 14, 15, -1]])

## 3) Array Operations & Broadcasting

**3.1** Compute element‑wise addition, subtraction, multiplication, and division of arrays `a=[1,2,3,4]` and `b=[10,20,30,40]`.

In [35]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[11 22 33 44]
[ -9 -18 -27 -36]
[ 10  40  90 160]
[0.1 0.1 0.1 0.1]


**3.2** Square all elements of `a` without using a Python loop.

In [36]:
a**2

array([ 1,  4,  9, 16])

**3.3** Let `A = np.ones((3,3))` and `v = np.array([1,2,3])`. Add `v` to each **row** of `A` using broadcasting.

In [39]:
A = np.ones(shape=(3, 3)) # 3, 3 --> 3, 3 --> 3, 3
v = np.array([1, 2, 3])   # 3    --> 1, 3 --> 3, 3
A + v

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

**3.4** Multiply each **column** of `A` by `[1,2,3]` using broadcasting.

In [40]:
A * v

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

**3.5** Normalize array `p = np.array([3.0, 4.0, 0.0, 8.0])` to unit length (divide by its Euclidean norm).

In [42]:
p = np.array([3, 4, 0, 8], dtype="float")
norm = np.linalg.norm(p)
p / norm

array([0.31799936, 0.42399915, 0.        , 0.8479983 ])

**3.6** Compute the pairwise sum of vectors in `X = np.array([[1,2],[3,4],[5,6]])` with `y = np.array([10,20])` via broadcasting (result shape 3×2).

In [44]:
X = np.array([[1, 2],
              [3, 4],
              [5, 6]])   # (3, 2) --> (3, 2) --> (3, 2)
y = np.array([10, 20])   # (2)    --> (1, 2) --> (3, 2)

X+y

array([[11, 22],
       [13, 24],
       [15, 26]])

**3.7** Given `B = np.arange(12).reshape(3,4)`, subtract the **column means** from each column (column‑wise centering) using broadcasting.

In [51]:
B = np.arange(12).reshape(3, 4)
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
B_mean = B.mean(axis=0, keepdims=True)
B_mean

array([[4., 5., 6., 7.]])

In [54]:
B - B_mean

array([[-4., -4., -4., -4.],
       [ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.]])

**3.8** Clip array values: given `w = np.array([-3, -1, 0, 2, 9])`, clip to the range `[0, 5]`.

In [56]:
w = np.array([-3, -1, 0, 2, 9])
w.clip(min=0, max=5)

array([0, 0, 0, 2, 5])

## 4) Mathematical Functions

**4.1** For `q = np.linspace(-2*np.pi, 2*np.pi, 50)`, compute `sin(q)`, `cos(q)`, and `tan(q)` arrays.

In [61]:
q = np.linspace(start=-2*np.pi, stop=2*np.pi, num=50)
print(np.sin(q)[:3])
print(np.cos(q)[:3])
print(np.tan(q)[:3])

[2.44929360e-16 2.53654584e-01 4.90717552e-01]
[1.         0.96729486 0.8713187 ]
[2.44929360e-16 2.62230881e-01 5.63189508e-01]


**4.2** Compute element‑wise `exp`, `log`, and `sqrt` for `r = np.array([1, e, e**2, 10.0])` (use `np.e` where needed).

In [66]:
r = np.array([1, np.e, np.e**2, 10])
print(np.exp(r))
print(np.log(r))
print(np.sqrt(r))

[2.71828183e+00 1.51542622e+01 1.61817799e+03 2.20264658e+04]
[0.         1.         2.         2.30258509]
[1.         1.64872127 2.71828183 3.16227766]


**4.3** Compute `np.floor`, `np.ceil`, and `np.round` for `s = np.array([1.2, 3.7, -2.3, -4.8])`.

In [67]:
s = np.array([1.2, 3.7, -2.3, -4.8])
print(np.floor(s))
print(np.ceil(s))
print(np.round(s))

[ 1.  3. -3. -5.]
[ 2.  4. -2. -4.]
[ 1.  4. -2. -5.]


**4.4** Safely compute `log1p(x)` for `x = np.array([0, 1e-10, 1e-5, 0.1])`. Why is `log1p` preferred here? (Answer in a comment)

In [71]:
x = np.array([0, 1e-10, 1e-5, 0.1])

# Because of the numbers are so close to 0 and tiny number we use lpg1p if we manually make like log(1 + x) 
# it gives us auto rounded number like 1 and the result will be 0 incorrectly

# Compute log(1 + x) safely
result_1 = np.log1p(x)

print(result_1)

[0.00000000e+00 1.00000000e-10 9.99995000e-06 9.53101798e-02]


**4.5** Compute the sigmoid function `σ(x) = 1 / (1 + exp(-x))` for `x = np.linspace(-8, 8, 9)`.

In [72]:
x = np.linspace(-8, 8, 9)
sigmoid = 1 / (1 + np.exp(-x))
sigmoid

array([3.35350130e-04, 2.47262316e-03, 1.79862100e-02, 1.19202922e-01,
       5.00000000e-01, 8.80797078e-01, 9.82013790e-01, 9.97527377e-01,
       9.99664650e-01])

**4.6** Standardize `t` (z‑score): given `t = np.array([10, 12, 9, 13, 11, 8])`, transform to mean 0 and std 1.

In [79]:
t = np.array([10, 12, 9, 13, 11, 8])

mean = np.mean(t)
std = np.std(t)

t_standardized = (t - mean) / std

print("original Array:", t)
print("Standardized Array:", t_standardized)
print("\nVerification:")
print("New Mean:", np.round(np.mean(t_standardized), 2))
print("New Std Dev:", np.std(t_standardized))

original Array: [10 12  9 13 11  8]
Standardized Array: [-0.29277002  0.87831007 -0.87831007  1.46385011  0.29277002 -1.46385011]

Verification:
New Mean: -0.0
New Std Dev: 1.0


## 5) Aggregations & Descriptive Stats

**5.1** Given `u = np.array([5, 5, 9, 1, 1, 9, 9])`, compute: mean, median, variance, std, min, max.

In [84]:
u = np.array([5, 5, 9, 1, 1, 9, 9])
print("mean:", np.mean(u))
print("median:", np.median(u))
print("variance:", np.var(u))
print("std dev:", np.std(u))
print("min:", u.min())
print("max:", u.max())

mean: 5.571428571428571
median: 5.0
variance: 11.10204081632653
std dev: 3.3319725113401715
min: 1
max: 9


**5.2** Compute `argmin` and `argmax` for `u`. What values do they point to? (Print index & value)

In [92]:
print(u)
print("min (index)", u.argmin())
print("min (value)", u[u.argmin()])
print("max (index)", u.argmax())
print("max (value)", u[u.argmax()])

[5 5 9 1 1 9 9]
min (index) 3
min (value) 1
max (index) 2
max (value) 9


**5.3** For `V = np.arange(12).reshape(3,4)`, compute **row sums** and **column means**.

In [100]:
V = np.arange(12).reshape(3,4)
print("data:\n", V)
print("row sums:\n", V.sum(axis=1, keepdims=True))
print("column means:\n", V.mean(axis=0, keepdims=True))

data:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
row sums:
 [[ 6]
 [22]
 [38]]
column means:
 [[4. 5. 6. 7.]]


**5.4** For `V`, compute the cumulative sum along axis 1 and the cumulative product along axis 0.

In [104]:
print("Cum sum within rows:\n", np.cumsum(V, axis=1))
print("Cum product within column:\n", np.cumprod(V, axis=0))

Cum sum within rows:
 [[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]
Cum product within column:
 [[  0   1   2   3]
 [  0   5  12  21]
 [  0  45 120 231]]


**5.5** For `u`, return the **unique** values and their **counts** (hint: `np.unique(..., return_counts=True)`).

In [106]:
np.unique(ar=u, return_counts=True)

(array([1, 5, 9]), array([2, 2, 3]))

**5.6** Compute the **50th percentile (median)** and **90th percentile** of `u` using `np.percentile`.

In [109]:
print(u)
print(np.percentile(a=u, q=50))
print(np.percentile(a=u, q=90))

[5 5 9 1 1 9 9]
5.0
9.0


## 6) Random Numbers & Simulations

**6.1** Set a random seed (e.g., 123). Generate 10 random numbers from the uniform distribution [0,1).

In [178]:
rng = np.random.default_rng(seed=123)
arr = rng.uniform(low=0, high=1, size=10)
arr

array([0.68235186, 0.05382102, 0.22035987, 0.18437181, 0.1759059 ,
       0.81209451, 0.923345  , 0.2765744 , 0.81975456, 0.88989269])

**6.2** Generate a 3×3 matrix of random integers between 1 and 100 (inclusive).

In [179]:
arr = rng.integers(low=1, high=100, size=(3, 3), endpoint=True)
arr

array([[ 3, 52, 27],
       [25, 25, 83],
       [80, 22, 41]])

**6.3** Draw 1,000 samples from a standard normal distribution and compute sample mean and std. Compare to theoretical values.

In [182]:
data = rng.standard_normal(size=1000)
print(np.mean(data))   # around 0 but not exacty 0
print(np.std(data))    # around 1 but not exactly 1

-0.019245183752936094
0.9855472315901597


**6.4** Simulate 1,000 fair coin flips (use 0/1). Estimate the probability of heads.

In [189]:
rng = np.random.default_rng(seed=1234)
head_and_tail = np.array([0, 1])
coin_flips = rng.choice(a=head_and_tail, size=1000, replace=True, p=[0.5, 0.5])
head = np.sum(coin_flips)
tail = coin_flips.size - head
print(f"Head: {head/coin_flips.size * 100}%")
print(f"Tail: {tail/coin_flips.size * 100}%")

Head: 50.2%
Tail: 49.8%


**6.5** Simulate rolling two fair dice 10,000 times. Estimate the probability that the sum equals 7.

In [194]:
rng_1 = np.random.default_rng(seed=1234)
rng_2 = np.random.default_rng(seed=4321)

dice_faces = np.array([1, 2, 3, 4, 5, 6])
dice_1 = rng_1.choice(a=dice_faces, size=10_000, replace=True, p=[1/6, 1/6, 1/6, 1/6, 1/6, 1/6])
dice_2 = rng_2.choice(a=dice_faces, size=10_000, replace=True, p=[1/6, 1/6, 1/6, 1/6, 1/6, 1/6])

dice_pair = dice_1 + dice_2
mask = dice_pair == 7
print("Estimated Probablity:", dice_pair[mask].size/10000)
print("Theoretical Probablity:", 6/36)

Estimated Probablity: 0.1704
Theoretical Probablity: 0.16666666666666666


**6.6** Draw 500 samples from a binomial distribution (n=20, p=0.4). Compute mean and variance; compare to theory.

In [198]:
rng = np.random.default_rng(seed=42)

n = 20
p = 0.4
size = 500
samples = rng.binomial(n=n, p=p, size=size)
sample_mean = np.mean(samples)
sample_variance = np.var(samples)
print(sample_mean)
print(sample_variance)

theo_mean = n * p
theo_var = n * p * (1 - p)
print(theo_mean)
print(theo_var)

7.976
4.451423999999999
8.0
4.8


**6.7** Use `np.random.multivariate_normal` to draw 1,000 2D samples with mean `[0,0]` and covariance `[[1,0.5],[0.5,1]]`. Compute the sample covariance matrix.

In [200]:
rng = np.random.default_rng(seed=42)
sample = rng.multivariate_normal(mean=[0, 0], cov=[[1, 0.5],[0.5, 1]], size=1000)
np.cov(m=sample, rowvar=False)

array([[1.04294927, 0.48054416],
       [0.48054416, 0.94411583]])

**6.8** Monte Carlo: Estimate π by randomly sampling 100,000 points in the unit square and counting how many fall inside the unit quarter‑circle.

In [201]:
# NOTE: Gemini Generated Answer
# Set a random seed for reproducible results
np.random.seed(42)

num_points = 100000

# 1. Generate random x and y coordinates uniformly distributed between 0 and 1
x = np.random.rand(num_points)
y = np.random.rand(num_points)

# 2. Calculate the squared distance from the origin (0,0) for all points
# Squaring avoids calculating a costly square root (sqrt) operation
distance_squared = x**2 + y**2

# 3. Count how many points have a distance <= 1
points_inside = np.sum(distance_squared <= 1)

# 4. Estimate pi
pi_estimate = 4 * (points_inside / num_points)

print(f"Points Inside: {points_inside:,} out of {num_points:,}")
print(f"Estimated π:   {pi_estimate}")
print(f"Actual π:      {np.pi}")
print(f"Absolute Error: {abs(np.pi - pi_estimate):.6f}")

Points Inside: 78,440 out of 100,000
Estimated π:   3.1376
Actual π:      3.141592653589793
Absolute Error: 0.003993


## 7) Linear Algebra

**7.1** Compute the dot product of `a = [1,2,3]` and `b = [4,5,6]`.

In [149]:
a = np.array([1, 2, 3])
b = np.array([4, 5 ,6])

# Method 1
a @ b

# Method 2
np.dot(a, b)

# Method 3
np.matmul(a, b)

np.int64(32)

**7.2** Given `A = [[2,1],[1,2]]`, compute determinant, inverse, and verify `A @ A_inv ≈ I`.

In [161]:
A = np.array([[2, 1],
              [1, 2]])

det = np.linalg.det(A)
A_inv = np.linalg.inv(A)
print(A)
print(det)
print(A_inv)
# Verify
print(A @ A_inv)

[[2 1]
 [1 2]]
2.9999999999999996
[[ 0.66666667 -0.33333333]
 [-0.33333333  0.66666667]]
[[1. 0.]
 [0. 1.]]


**7.3** For `A` above, compute eigenvalues and eigenvectors, and verify `A @ v ≈ λ v`.

In [162]:
eigvalues, eigenvector = np.linalg.eig(A)
print(eigvalues)
print(eigenvector)

# Verify
print((A @ eigenvector) == (eigvalues * eigenvector))

[3. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[[ True  True]
 [ True  True]]


**7.4** Solve the linear system `3x + 2y = 7` and `2x + 5y = 8`.

In [163]:
A = np.array([[3, 2],
              [2, 5]])

b = np.array([7, 8])

x = np.linalg.solve(A, b)
x

array([1.72727273, 0.90909091])

**7.5** Create a random 4×4 matrix and compute its **rank**.

In [166]:
rng = np.random.default_rng(seed=1234)
M = rng.integers(low=1, high=10, size=(4, 4))
rank = np.linalg.matrix_rank(M)
rank

np.int64(4)

**7.6** Perform QR decomposition of a random 4×3 matrix and verify `Q @ R ≈ A`.

In [169]:
A = rng.integers(low=1, high=10, size=(4, 3))

Q, R = np.linalg.qr(A)

# Verify
is_equal = np.allclose(Q @ R, A)
is_equal

True

## 8) Reshaping, Stacking & Splitting

**8.1** Create `a = np.arange(24)` and reshape to (4,6).

In [110]:
a = np.arange(24).reshape(4, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

**8.2** From the (4,6) array, extract a (2,3) block from the center.

In [120]:
# Slicnig Method
a[1:-1, 1:-2]

array([[ 7,  8,  9],
       [13, 14, 15]])

In [119]:
# Boolean indexing - Masking method
mask = np.zeros(shape=(4,6), dtype="bool")
mask[1:-1, 1:-2] = True
a[mask].reshape(2, 3)

array([[ 7,  8,  9],
       [13, 14, 15]])

**8.3** Vertically stack two arrays of shape (2,3) to obtain (4,3); then horizontally stack to obtain (2,6).

In [122]:
arr_1 = np.array([[1, 2, 3],
                  [4, 5, 6]])

arr_2 = np.array([[7, 8, 9],
                  [1, 2, 3]])

In [123]:
np.vstack((arr_1, arr_2)) # (4, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [125]:
np.hstack((arr_1, arr_2)) # (2, 6)

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 1, 2, 3]])

**8.4** Split an array of length 20 into 4 equal parts; then split into parts of lengths `[3,5,12]`.

In [126]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [127]:
np.split(arr, 4)

[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19])]

In [135]:
np.split(arr, [3, 8])

[array([0, 1, 2]),
 array([3, 4, 5, 6, 7]),
 array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])]

**8.5** Use `np.concatenate` to combine three arrays along axis 0 and along axis 1 (where shapes allow).

In [146]:
arr_1 = np.array([[1, 2, 3]])
arr_2 = np.array([[4, 5, 6]])
arr_3 = np.array([[7, 8, 9]])

print(np.concatenate((arr_1, arr_2, arr_3), axis=0))
print(np.concatenate([arr_1, arr_2, arr_3], axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]


## 9) Real‑World Mini Case Studies

**9.1 Finance**: Prices of a stock for 10 days are `p = [100, 102, 101, 103, 105, 104, 106, 107, 110, 108]`. Compute **daily returns** (percentage) and **cumulative return**.

In [212]:
prices = np.array([100, 102, 101, 103, 105, 104, 106, 107, 110, 108])
windows = np.lib.stride_tricks.sliding_window_view(x=prices, window_shape=2)
yesterdays = windows[:, 0]
todays = windows[:, 1]
daily_returns = ((todays - yesterdays) / yesterdays) * 100
print("Daily Returns:\n", daily_returns)
print("Cumulative Returns:\n", np.cumsum(daily_returns))

Daily Returns:
 [ 2.         -0.98039216  1.98019802  1.94174757 -0.95238095  1.92307692
  0.94339623  2.80373832 -1.81818182]
Cumulative Returns:
 [2.         1.01960784 2.99980586 4.94155344 3.98917248 5.91224941
 6.85564563 9.65938395 7.84120213]


**9.2 Demography**: Ages of 20 people are in an array. Compute mean, median, std, and the proportion aged 18–30. *(Generate random integers 10–80 with a fixed seed.)*

In [218]:
rng = np.random.default_rng(seed=67)
ages = rng.integers(low=10, high=80, size=20, endpoint=True)
mask = (ages >= 18) & (ages <= 30)
masked_ages = ages[mask].size
proprtion = masked_ages / 20
print("Mean age:", np.mean(ages))
print("Median age:", np.median(ages))
print("Std. Dev:", np.std(ages))
print("18-30 ages:", proprtion)

Mean age: 42.95
Median age: 40.5
Std. Dev: 17.115709158547887
18-30 ages: 0.1


**9.3 Quality Control**: Simulate 1,000 measurements with true value 50 and measurement noise `N(0, 2^2)`. What fraction of measurements fall within ±3 of the true value?

In [222]:
rng = np.random.default_rng(seed=1234)
samples = rng.normal(loc=50, scale=2, size=1000)
mask = (samples >= 47) & (samples <= 53)
samples[mask].size / 1000

0.851

**9.4 A/B Testing**: Variant A converts 48/500 users; Variant B converts 62/500. Compute conversion rates and the **absolute lift** (B−A). Simulate 10,000 bootstrap samples of the lift.

In [246]:
# NOTE: Gemini generated answer.
# Experimental Data
n_A, conv_A = 500, 48
n_B, conv_B = 500, 62

# Create raw user outcome arrays (1 = converted, 0 = did not convert)
data_A = np.zeros(n_A)
data_A[:conv_A] = 1

data_B = np.zeros(n_B)
data_B[:conv_B] = 1

# Setup bootstrapping parameters
np.random.seed(42)
n_bootstraps = 10000

# Draw 10,000 bootstrap samples for both variants (with replacement)
# Generating a 10000x500 matrix and calculating the mean along rows (axis=1)
boot_cr_A = np.random.choice(data_A, size=(n_bootstraps, n_A), replace=True).mean(axis=1)
boot_cr_B = np.random.choice(data_B, size=(n_bootstraps, n_B), replace=True).mean(axis=1)

# Calculate simulated absolute lifts
boot_lifts = boot_cr_B - boot_cr_A

# Compute 95% Confidence Interval (2.5th to 97.5th percentile)
ci_lower, ci_upper = np.percentile(boot_lifts, [2.5, 97.5])

# Compute probability that Variant B is truly better than Variant A
prob_b_better = np.mean(boot_lifts > 0)

print(f"Observed Absolute Lift: {conv_B/n_B - conv_A/n_A:+.4%}")
print(f"Mean Bootstrap Lift:   {np.mean(boot_lifts):+.4%}")
print(f"95% Confidence Interval: [{ci_lower:+.4%}, {ci_upper:+.4%}]")
print(f"Probability that B > A:  {prob_b_better:.2%}")

Observed Absolute Lift: +2.8000%
Mean Bootstrap Lift:   +2.7762%
95% Confidence Interval: [-1.0000%, +6.6000%]
Probability that B > A:  91.16%


**9.5 Sports Analytics**: Given player scores over 8 games, compute moving average with window size 3 using vectorized operations (no loops). *(Generate random integers 0–30.)*

In [227]:
rng = np.random.default_rng(seed=1234)
scores = rng.integers(low=0, high=30, size=8, endpoint=True)
windows = np.lib.stride_tricks.sliding_window_view(x=scores, window_shape=3)
moving_averages = np.mean(a=windows, axis=1, keepdims=True)
print("Scores:\n",scores)
print("Windows:\n", windows)
print("Moving Averages:\n", moving_averages)

Scores:
 [30 30 30 11  5 28  3  8]
Windows:
 [[30 30 30]
 [30 30 11]
 [30 11  5]
 [11  5 28]
 [ 5 28  3]
 [28  3  8]]
Moving Averages:
 [[30.        ]
 [23.66666667]
 [15.33333333]
 [14.66666667]
 [12.        ]
 [13.        ]]


**9.6 Image Mini‑Task**: Create a 10×10 grayscale image as a NumPy array with a white square (value 255) in the center and 0 elsewhere. Compute its mean pixel value.

In [244]:
image = np.zeros(shape=(10,10), dtype="int")
windows = np.lib.stride_tricks.sliding_window_view(x=image, window_shape=(4, 4), writeable=True)
windows[3, 3] = 255
print(image)

[[  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0 255 255 255 255   0   0   0]
 [  0   0   0 255 255 255 255   0   0   0]
 [  0   0   0 255 255 255 255   0   0   0]
 [  0   0   0 255 255 255 255   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]]


**9.7 Logistics**: There are 5 warehouses with inventories `[40, 55, 20, 80, 60]` and 4 stores with demands `[30, 50, 40, 35]`. Using NumPy (not loops), compute how many units remain after fulfilling demands sequentially from warehouses.

In [247]:
warehouse_inventor = np.array([40, 55, 20, 80, 60])
store_demands = np.array([30, 50, 40, 35])
np.full(shape=store_demands.size, fill_value=np.sum(warehouse_inventor)) - np.cumsum(store_demands)

array([225, 175, 135, 100])